In [58]:
import pandas as pd
import numpy as np


In [59]:
faqs= """Hi my name is sandeep muhal.
I am from ajmer.
current i live in bikaner.
and focus on my future.
my background is technical.
and my collage nane is bikaner technical university.
that is my profile.
and i know some programming language like java python c++ javascripts.
i am a good person and i become a ai engineer.
"""

In [60]:
from tensorflow import keras

In [61]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [62]:
tokenizer=Tokenizer()

In [63]:
tokenizer.fit_on_texts([faqs])

In [64]:
tokenizer.word_index

{'my': 1,
 'i': 2,
 'is': 3,
 'and': 4,
 'am': 5,
 'bikaner': 6,
 'technical': 7,
 'a': 8,
 'hi': 9,
 'name': 10,
 'sandeep': 11,
 'muhal': 12,
 'from': 13,
 'ajmer': 14,
 'current': 15,
 'live': 16,
 'in': 17,
 'focus': 18,
 'on': 19,
 'future': 20,
 'background': 21,
 'collage': 22,
 'nane': 23,
 'university': 24,
 'that': 25,
 'profile': 26,
 'know': 27,
 'some': 28,
 'programming': 29,
 'language': 30,
 'like': 31,
 'java': 32,
 'python': 33,
 'c': 34,
 'javascripts': 35,
 'good': 36,
 'person': 37,
 'become': 38,
 'ai': 39,
 'engineer': 40}

In [65]:
input_sentence=[]
for sentence in faqs.split('\n'):
    # print(sentence)
    #  X=tokenizer.texts_to_sequences([sentence])[0]
    token=tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1,len(token)):
        input_sentence.append(token[:i+1])


In [66]:
input_sentence

[[9, 1],
 [9, 1, 10],
 [9, 1, 10, 3],
 [9, 1, 10, 3, 11],
 [9, 1, 10, 3, 11, 12],
 [2, 5],
 [2, 5, 13],
 [2, 5, 13, 14],
 [15, 2],
 [15, 2, 16],
 [15, 2, 16, 17],
 [15, 2, 16, 17, 6],
 [4, 18],
 [4, 18, 19],
 [4, 18, 19, 1],
 [4, 18, 19, 1, 20],
 [1, 21],
 [1, 21, 3],
 [1, 21, 3, 7],
 [4, 1],
 [4, 1, 22],
 [4, 1, 22, 23],
 [4, 1, 22, 23, 3],
 [4, 1, 22, 23, 3, 6],
 [4, 1, 22, 23, 3, 6, 7],
 [4, 1, 22, 23, 3, 6, 7, 24],
 [25, 3],
 [25, 3, 1],
 [25, 3, 1, 26],
 [4, 2],
 [4, 2, 27],
 [4, 2, 27, 28],
 [4, 2, 27, 28, 29],
 [4, 2, 27, 28, 29, 30],
 [4, 2, 27, 28, 29, 30, 31],
 [4, 2, 27, 28, 29, 30, 31, 32],
 [4, 2, 27, 28, 29, 30, 31, 32, 33],
 [4, 2, 27, 28, 29, 30, 31, 32, 33, 34],
 [4, 2, 27, 28, 29, 30, 31, 32, 33, 34, 35],
 [2, 5],
 [2, 5, 8],
 [2, 5, 8, 36],
 [2, 5, 8, 36, 37],
 [2, 5, 8, 36, 37, 4],
 [2, 5, 8, 36, 37, 4, 2],
 [2, 5, 8, 36, 37, 4, 2, 38],
 [2, 5, 8, 36, 37, 4, 2, 38, 8],
 [2, 5, 8, 36, 37, 4, 2, 38, 8, 39],
 [2, 5, 8, 36, 37, 4, 2, 38, 8, 39, 40]]

In [67]:
max_len=max([len(i) for i in input_sentence])

In [68]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input=pad_sequences(input_sentence,maxlen=max_len,padding='pre')

In [69]:
padded_input

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  1, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  9,  1, 10,  3],
       [ 0,  0,  0,  0,  0,  0,  9,  1, 10,  3, 11],
       [ 0,  0,  0,  0,  0,  9,  1, 10,  3, 11, 12],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  5, 13],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  5, 13, 14],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 15,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 15,  2, 16],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  2, 16, 17],
       [ 0,  0,  0,  0,  0,  0, 15,  2, 16, 17,  6],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4, 18],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4, 18, 19],
       [ 0,  0,  0,  0,  0,  0,  0,  4, 18, 19,  1],
       [ 0,  0,  0,  0,  0,  0,  4, 18, 19,  1, 20],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 21],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 21,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  1, 21,  3

In [70]:
X=padded_input[:,:-1]
y=padded_input[:,-1]

In [71]:
X

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  9,  1, 10],
       [ 0,  0,  0,  0,  0,  0,  9,  1, 10,  3],
       [ 0,  0,  0,  0,  0,  9,  1, 10,  3, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  5, 13],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 15],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 15,  2],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  2, 16],
       [ 0,  0,  0,  0,  0,  0, 15,  2, 16, 17],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4, 18],
       [ 0,  0,  0,  0,  0,  0,  0,  4, 18, 19],
       [ 0,  0,  0,  0,  0,  0,  4, 18, 19,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 21],
       [ 0,  0,  0,  0,  0,  0,  0,  1, 21,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4],
       [ 0,  0,  0, 

In [72]:
y

array([ 1, 10,  3, 11, 12,  5, 13, 14,  2, 16, 17,  6, 18, 19,  1, 20, 21,
        3,  7,  1, 22, 23,  3,  6,  7, 24,  3,  1, 26,  2, 27, 28, 29, 30,
       31, 32, 33, 34, 35,  5,  8, 36, 37,  4,  2, 38,  8, 39, 40],
      dtype=int32)

In [73]:
X.shape

(49, 10)

In [74]:
y.shape

(49,)

In [75]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=41)

In [76]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [77]:
len(tokenizer.word_index)

40

In [78]:
y.shape

(49, 41)

In [79]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [80]:
# X,y

In [81]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [82]:
vocab_size = len(tokenizer.word_index) + 1 
vocab_size

41

In [95]:
model=Sequential()
# model.add(Embedding(vocab_size,12,input_length=10))
model.add(Embedding(input_dim=vocab_size, output_dim=8, input_length=10))
model.add(LSTM(30))
model.build(input_shape=(None,2))
model.add(Dense(41,activation='softmax'))

In [96]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [97]:
model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 2, 8)           │           328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_13 (LSTM)                  │ (None, 30)             │         4,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 41)             │         1,271 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,279 (24.53 KB)

 Trainable params: 6,279 (24.53 KB)

 Non-trainable params: 0 (0.00 B)

In [102]:
model.fit(X,y,epochs=80)

Epoch 1/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6437 - loss: 1.4956
Epoch 2/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6333 - loss: 1.5186
Epoch 3/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6541 - loss: 1.4814
Epoch 4/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6437 - loss: 1.4775
Epoch 5/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6645 - loss: 1.4658
Epoch 6/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6541 - loss: 1.4875
Epoch 7/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6541 - loss: 1.4372 
Epoch 8/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6437 - loss: 1.4588
Epoch 9/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6333 - loss: 1.4563
Epoch 10/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6333 - loss: 1.4789
Epoch 11/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6437 - loss: 1.4496 
Epoch 12/80
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6750 - loss: 1.3691
E

In [105]:
import time
text = "i from  "

for i in range(5):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
i from   my
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
i from   my is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
i from   my is name
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
i from   my is name is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
i from   my is name is sandeep
